# cmake file for SparkFun MicroMod RP2040
set(PICO_BOARD sparkfun_micromod)

set(MICROPY_PY_NETWORK_WIZNET5K W5500)
set(WIZNET_CHIP W5500)
set(MICROPY_PY_LWIP 1)

set(MICROPY_FROZEN_MANIFEST ${CMAKE_SOURCE_DIR}/boards/SPARKFUN_MICROMOD_RP2040_EFB_W5500/manifest.py)